[package]
name = "byte_arithmetic"
version = "0.2.0"
edition = "2021"
description = "Implementation of simple arithmetic on byte-like objects"
license-file = "LICENSE"
exclude = [".idea/*"]

[dependencies]
itertools = "0.10"